brace_style = "PreferSameLine"
condense_wildcard_suffixes = true
fn_args_layout = "Compressed"
format_code_in_doc_comments = true
hard_tabs = true
imports_layout = "HorizontalVertical"
imports_granularity = "Module"
reorder_impl_items = true
group_imports = "StdExternalCrate"
tab_spaces = 2
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
max_width = 120
where_single_line = true
normalize_comments = true
normalize_doc_attributes = true