[build]
target = 'mipsel-sony-psx.json'

[unstable]
build-std = ['core']
build-std-features = ['compiler-builtins-mem']

[target.mipsel-sony-psx]
rustflags = ['-Clink-arg=-Tpsexe.ld', '-Clink-arg=--oformat=binary']
runner = ['mednafen']